<h3>Slider owl</h3>
    <div class="owl-carousel owl-theme">
        <div class="item">My content 1</div>
        <div class="item">My content 2</div>
        <div class="item">My content 3</div>
        <div class="item">My content 4</div>
        <div class="item">My content 5</div>
        <div class="item">My content 6</div>
        <div class="item">My content 7</div>
        <div class="item">My content 8</div>
        <div class="item">My content 9</div>
        <div class="item">My content 10</div>
    </div>
<script>
    require([
        'jquery',
        'jquery/ui',
        'owl'
    ], function ($) {
        $(document).ready(function(){
            $(".owl-carousel").owlCarousel({
                center: true,
                nav:true,
                loop: false,
                margin: 15,
                autoWidth: true,
                responsive: {
                    0:{
                        nav:false,
                        center: false
                    },
                    768:{
                        items:3,
                        nav:true,
                        center: false
                    },
                    1024:{
                        items:3,
                        nav:true,
                        loop: true,
                        autoWidth: false
                    },
                    1440:{
                        items:4,
                        nav:true,
                        loop:true,
                        autoWidth: false
                    }
                }
            });
        });
    });
</script>
