<h3>Slider owl</h3>
<div class="owl-carousel owl-theme">
    <div class="item">My content 1</div>
    <div class="item">My content 2</div>
    <div class="item">My content 3</div>
    <div class="item">My content 4</div>
    <div class="item">My content 5</div>
    <div class="item">My content 6</div>
    <div class="item">My content 7</div>
    <div class="item">My content 8</div>
    <div class="item">My content 9</div>
    <div class="item">My content 10</div>
</div>
<script type="text/x-magento-init">
    {
        ".owl-carousel": {
            "js/sliderinit": {
                "items": 2,
                "margin": 10,
                "dots": false,
                "loop": false
            }
        }
    }
</script>
