<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <span><?= $block->escapeHtml($block->getCopyright()) ?></span>
</small>
test copy

<script type="text/x-magento-init">
    {
        "*": {
            "js/owl.carousel": {}
        },
        ".copyright": {
            "js/removeCopyright": {}
        }
    }
</script>