<div class="h2-container">
    <h2>OFFICIAL DISTRIBUTORS OF</h2>
</div>
<div class="owl-carousel owl-theme distributors">
    <div class="item"><span>First</span></div>
    <div class="item"><span>Second</span></div>
    <div class="item"><span>Third</span></div>
    <div class="item"><span>Fourth</span></div>
    <div class="item"><span>Fifth</span></div>
    <div class="item"><span>Sixth</span></div>
    <div class="item"><span>Seventh</span></div>
    <div class="item"><span>Eighth</span></div>
    <div class="item"><span>Ninth</span></div>
    <div class="item"><span>Tenth</span></div>
    <div class="item"><span>Eleventh</span></div>
    <div class="item"><span>Twelfth</span></div>
</div>

<script type="text/x-magento-init">
    {
        ".owl-carousel": {
            "js/sliderinit": {
                "loop": true,
                "autoWidth": false,
                "responsive": {
                    "0": {
                        "dots": false,
                        "items": 1,
                        "center": true,
                        "nav": true
                    },
                    "768": {
                        "dots": true,
                        "nav": false,
                        "items": 4
                    },
                    "1024": {
                        "nav": true,
                        "items": 6
                    }
                }
            }
        }
    }
</script>
