<div class="footer-links-new">
    <div class="footer-container-left">
        <div class="links-new links-information">
            <h4>Information</h4>
            <ul>
                <li class="links-item"><a href="#">About Us</a></li>
                <li class="links-item"><a href="#">Privacy Policy</a></li>
                <li class="links-item"><a href="#">Terms & Conditions</a></li>
                <li class="links-item"><a href="#">Secure payment</a></li>
            </ul>
        </div>

        <div class="links-new links-customer-service">
            <h4>Customer Service</h4>
            <ul>
                <li class="links-item"><a href="#">Contact Us</a></li>
                <li class="links-item"><a href="#">Return</a></li>
                <li class="links-item"><a href="#">FAQ</a></li>
                <li class="links-item"><a href="#">Site Map</a></li>
            </ul>
        </div>

        <div class="links-new links-extras">
            <h4>Extras</h4>
            <ul>
                <li class="links-item"><a href="#">Brands</a></li>
                <li class="links-item"><a href="#">Gift Vouchers</a></li>
                <li class="links-item"><a href="#">Affiliates</a></li>
                <li class="links-item"><a href="#">Specials</a></li>
            </ul>
        </div>

        <div class="links-new links-my-account">
            <h4>My Account</h4>
            <ul>
                <li class="links-item"><a href="#">My Account</a></li>
                <li class="links-item"><a href="#">Order History</a></li>
                <li class="links-item"><a href="#">Wish List</a></li>
                <li class="links-item"><a href="#">Newsletter</a></li>
            </ul>
        </div>
    </div>

    <div class="links-new follow footer-container-right">
        <h3>Follow us on social networks</h3>
        <ul class="ul-display-inline">
            <li class="follow-item facebook"><a href="#"><img src='<?php echo $this->getViewFileUrl('images/follow-facebook.png'); ?>' alt="facebook"></a></li>
            <li class="follow-item twitter"><a href="#"><img src='<?php echo $this->getViewFileUrl('images/follow-twitter.png'); ?>' alt="twitter"></a></li>
            <li class="follow-item google-plus"><a href="#"><img src='<?php echo $this->getViewFileUrl('images/follow-google-plus.png'); ?>' alt="google-plus"></a></li>
            <li class="follow-item linkedin"><a href="#"><img src='<?php echo $this->getViewFileUrl('images/follow-linkedin.png'); ?>' alt="linkedin"></a></li>
        </ul>
    </div>
</div>
