<div class="footer-links-bottom">
    <p class="links-bottom bottom-copyright">Copyright © ItemBridge inc., 2012</p>
    <a href="#" class="links-bottom bottom-address">Avenue of the American Ind., st.133/2, New York City, USA</a>
    <div class="links-bottom bottom-telephone">
        <span>Call Us:</span>
        <a href="tel:+380979895555" class="bottom-phone">+38 (097) 989-55-55</a>
        <span>or</span>
        <a href="tel:+380991235555" class="bottom-phone">+38 (099) 123-55-55</a>
    </div>
    <div class="links-bottom bottom-payments">
        <ul class="ul-display-inline">
            <li><a href="#" class="payments-visa"><img src='<?php echo $this->getViewFileUrl('images/payments-visa.png'); ?>' alt="visa"></a></li>
            <li><a href="#" class="payments-paypal"><img src='<?php echo $this->getViewFileUrl('images/payments-paypal.png'); ?>' alt="paypal"></a></li>
            <li><a href="#" class="payments-master"><img src='<?php echo $this->getViewFileUrl('images/payments-master.png'); ?>' alt="master"></a></li>
            <li><a href="#" class="payments-wu"><img src='<?php echo $this->getViewFileUrl('images/payments-wu.png'); ?>' alt="wu"></a></li>
        </ul>
    </div>
</div>
